const trackables = [
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/14133.gif",
    "name":"6. Internationales EarthCache Event 2025 Trackable",
    "originName":"",
    "updated":"2025-10-13 14:45:04",
    "owner":"",
    "publicCode":"TBB7R8Z",
    "privateCode":"ECE7V4",
    "Unnamed: 9":"",
    "mainPicture":"Undularia_Scalata.webp",
    "note":"Turmschnecke",
    "activateCode":"6IEE",
    "PIN":"",
    "tagsString":"Fossil, IEE, Event, Mega, 2025",
    "collectionsString":"Earthcache, Events"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/14133.gif",
    "name":"6. Internationales EarthCache Event 2025 Trackable",
    "originName":"",
    "updated":"2025-10-13 14:45:05",
    "owner":"",
    "publicCode":"TBB7NFA",
    "privateCode":"EC9DT2",
    "Unnamed: 9":"",
    "mainPicture":"Ammonit-1.webp",
    "note":"Ammonit",
    "activateCode":"6IEE",
    "PIN":"",
    "tagsString":"Fossil, IEE, Event, Mega, 2025",
    "collectionsString":"Earthcache, Events"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/14133.gif",
    "name":"6. Internationales EarthCache Event 2025 Trackable",
    "originName":"",
    "updated":"2025-10-13 14:45:03",
    "owner":"",
    "publicCode":"TBB7N38",
    "privateCode":"ECR14Y",
    "Unnamed: 9":"",
    "mainPicture":"Dino-1.webp",
    "note":"Dino Skelett",
    "activateCode":"6IEE",
    "PIN":"",
    "tagsString":"Fossil, IEE, Event, Mega, 2025",
    "collectionsString":"Earthcache, Events"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/14114.gif",
    "name":"HQ Blockparty \"Geocaching Friendship\" Trackable",
    "originName":"",
    "updated":"2025-10-13 14:44:52",
    "owner":"",
    "publicCode":"TBB7DA6",
    "privateCode":"GF97NV",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Event, Blockparty, 2025",
    "collectionsString":"Events"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/14008.gif",
    "name":"Bunker Block Party 2025 Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:44:54",
    "owner":"",
    "publicCode":"TBB5K19",
    "privateCode":"25H485",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Event, Blockparty, 2025",
    "collectionsString":"Events"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/13916.gif",
    "name":"Rocky Mountain National Park Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:45:00",
    "owner":"",
    "publicCode":"TBB4B13",
    "privateCode":"GS6WP0",
    "Unnamed: 9":"",
    "mainPicture":"Rocky-Mountain-National-Park-Both_600w.jpg",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Arrowhead",
    "collectionsString":"National Parks, USA"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/13905.gif",
    "name":"Block Party Gaswerk Augsburg Trackable",
    "originName":"",
    "updated":"2025-10-13 14:44:50",
    "owner":"",
    "publicCode":"TBB46BC",
    "privateCode":"GAW1KA",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Event, Blockparty, 2025",
    "collectionsString":"Events"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/13905.gif",
    "name":"Block Party Gaswerk Augsburg Trackable",
    "originName":"",
    "updated":"2025-10-13 14:44:51",
    "owner":"",
    "publicCode":"TBB463J",
    "privateCode":"GAV2NT",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Event, Blockparty, 2025",
    "collectionsString":"Events"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/23.gif",
    "name":"Indiana Jones Coin",
    "originName":"",
    "updated":"2025-10-15 07:47:49",
    "owner":"",
    "publicCode":"TBB0878",
    "privateCode":"INTER8",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Staubfinger",
    "collectionsString":"Geocache"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/13722.gif",
    "name":"BOCK auf BLOCK Geocoin",
    "originName":"",
    "updated":"2025-10-15 08:30:25",
    "owner":"",
    "publicCode":"TBAZQR2",
    "privateCode":"BBZPY0",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Event, 2025, Blockparty",
    "collectionsString":"Events"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/11346.gif",
    "name":"10000 Cache Milestone Coin and Tag Set",
    "originName":"",
    "updated":"2025-10-15 10:42:38",
    "owner":"",
    "publicCode":"TBAZE3K",
    "privateCode":"MSFFE6",
    "Unnamed: 9":"",
    "mainPicture":"milestone-tag-10000.jpg",
    "note":"",
    "activateCode":"MILESTONE",
    "PIN":"",
    "tagsString":"Achievment",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/11346.gif",
    "name":"10000 Cache Milestone Coin and Tag Set",
    "originName":"",
    "updated":"2025-10-15 10:42:39",
    "owner":"",
    "publicCode":"TBAZE0M",
    "privateCode":"MSKZZE",
    "Unnamed: 9":"",
    "mainPicture":"milestone_10000.jpg",
    "note":"",
    "activateCode":"MILESTONE",
    "PIN":"",
    "tagsString":"Achievment",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/13677.gif",
    "name":"Brockenevent Geocoin 2024",
    "originName":"",
    "updated":"2025-10-14 16:20:11",
    "owner":"",
    "publicCode":"TBAZ2M4",
    "privateCode":"BEWZE5",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"10. Brockenfrühstück 21.12.2024 GCAHGXH",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Event, Mega, Brocken, 2024",
    "collectionsString":"Events"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/23.gif",
    "name":"Geoswag C&P Club July 2024 - The Elemelons",
    "originName":"",
    "updated":"2025-10-14 16:25:36",
    "owner":"",
    "publicCode":"TBAX1B9",
    "privateCode":"CPT9DB",
    "Unnamed: 9":"",
    "mainPicture":"Geoswag-CP-Club-July-2024-The-Elemelons_600w.jpg",
    "note":"Vier 4 Elemente, die vier Elemente sind als kleine Magnete auf der Coin befestigt. Spruch auf der Coin: IF WATERMELONS EXIST, WHY ISN'T THERE FIREMELON, EARTHMELON, AND AIRMELON? Inklusive ein PIN",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Feuer, Wasser, Erde, Luft, Elemente, Wassermelone",
    "collectionsString":"Earthcache, Geoswag Coin & Pin Club"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/13556.gif",
    "name":"International EarthCache Day - Basalt",
    "originName":"",
    "updated":"2025-10-16 08:23:58",
    "owner":"",
    "publicCode":"TBAW73D",
    "privateCode":"EC2XQA",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/13556.gif",
    "name":"International EarthCache Day - Basalt",
    "originName":"",
    "updated":"2025-10-16 08:21:32",
    "owner":"",
    "publicCode":"TBAW73D",
    "privateCode":"EC2XQA",
    "Unnamed: 9":"",
    "mainPicture":"International-EarthCache-Day-Basalt-antik-silber.jpg",
    "note":"Coin 21\/85, https:\/\/www.geocaching.com\/track\/details.aspx?tracker=GTTR6T",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Basalt, 2024, Olivin",
    "collectionsString":"Earthcache"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/13556.gif",
    "name":"International EarthCache Day - Basalt",
    "originName":"",
    "updated":"2025-10-16 08:27:42",
    "owner":"",
    "publicCode":"TBAW72H",
    "privateCode":"ECHPB3",
    "Unnamed: 9":"",
    "mainPicture":"International-EarthCache-Day-Basalt-black-nickel.jpg",
    "note":"Coin 21\/85 https:\/\/www.geocaching.com\/track\/details.aspx?tracker=GTTR6T",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Basalt, 2024, Olivin",
    "collectionsString":"Earthcache"
  },
  {
    "iconURL":"https:\/\/img.geocaching.com\/largeicon\/6d4a20bf-a5f2-4e2f-93f4-b9cdc3ad93a0.png",
    "name":"IN VINO VERITAS GEOCOIN",
    "originName":"",
    "updated":"2025-10-13 14:27:08",
    "owner":"",
    "publicCode":"TBAVKWV",
    "privateCode":"CCMKX5",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"Weinglas mit Weißwein und Traubenrebe",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Wein, Traube, Rebe, Glas, Trinken",
    "collectionsString":"Essen und Trinken"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/13376.gif",
    "name":"Love Nature Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:27:01",
    "owner":"",
    "publicCode":"TBAV3E6",
    "privateCode":"LN1W6X",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"Love Nature Otter",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/13432.gif",
    "name":"Find a good spot - German Reviewer Coin 2024 (open blue)",
    "originName":"",
    "updated":"2025-10-14 16:24:41",
    "owner":"",
    "publicCode":"TBATH0F",
    "privateCode":"GRKJDK",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"Großer Karten PIN mit Signal, Ammonit",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/23.gif",
    "name":"Geoswag C&P Club January 2024 - Toss Back a Cold One!",
    "originName":"",
    "updated":"2025-10-13 14:44:49",
    "owner":"",
    "publicCode":"TBAQKWE",
    "privateCode":"CP04RY",
    "Unnamed: 9":"",
    "mainPicture":"toss-bierdose.jpg",
    "note":"Mit PIN (prüfen)",
    "activateCode":"",
    "PIN":"ja",
    "tagsString":"2024",
    "collectionsString":"Geoswag Coin & Pin Club"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/23.gif",
    "name":"Mount Rainier Arrowhead",
    "originName":"",
    "updated":"2025-10-13 14:45:01",
    "owner":"",
    "publicCode":"TBAQ26M",
    "privateCode":"GS8N2Y",
    "Unnamed: 9":"",
    "mainPicture":"Mount-Rainier-Arrowhead_600w.jpg",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Arrowhead",
    "collectionsString":"National Parks, USA"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/23.gif",
    "name":"Geoswag C&P Club January 2023 - Geocacher Greatest Hits",
    "originName":"",
    "updated":"2025-10-16 07:56:44",
    "owner":"",
    "publicCode":"TBAQ265",
    "privateCode":"GS3VKH",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"mit Pin. Seite A: Geocacher Greatest Hits, Seite B: First to Find Classics",
    "activateCode":"",
    "PIN":"",
    "tagsString":"2023",
    "collectionsString":"Geoswag Coin & Pin Club"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/13220.gif",
    "name":"Brockenevent Geocoin 2023",
    "originName":"",
    "updated":"2025-10-13 14:44:50",
    "owner":"",
    "publicCode":"TBANTVE",
    "privateCode":"BECNGA",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Event, Mega, 2023",
    "collectionsString":"Events"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/11346.gif",
    "name":"CachingFoXs 10000st Cache - Panzerknacker (GC8E3B9)",
    "originName":"10000 Cache Milestone Coin and Tag Set",
    "updated":"2025-10-14 16:53:31",
    "owner":"CachingFoX",
    "publicCode":"TBAN4H0",
    "privateCode":"MS085F",
    "Unnamed: 9":"",
    "mainPicture":"milestone_10000.jpg",
    "note":"",
    "activateCode":"MILESTONE",
    "PIN":"",
    "tagsString":"Achievment",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/11346.gif",
    "name":"10000 Funde später....",
    "originName":"10000 Cache Milestone Coin and Tag Set",
    "updated":"2025-10-13 14:44:48",
    "owner":"CachingFoX",
    "publicCode":"TBAN4DB",
    "privateCode":"MST53T",
    "Unnamed: 9":"",
    "mainPicture":"milestone-tag-10000.jpg",
    "note":"",
    "activateCode":"MILESTONE",
    "PIN":"",
    "tagsString":"Achievment",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/11326.gif",
    "name":"CachingFoX first find",
    "originName":"1st Cache Milestone Coin and Tag Set",
    "updated":"2025-10-13 14:44:47",
    "owner":"CachingFoX",
    "publicCode":"TBAB1DX",
    "privateCode":"MS57GD",
    "Unnamed: 9":"",
    "mainPicture":"milestone-tag-1st-find.jpg",
    "note":"",
    "activateCode":"MILESTONE",
    "PIN":"",
    "tagsString":"Achievment",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/11326.gif",
    "name":"CachingFoXs 1st Cache - Franz-Köhl-Turm-Cache (GCH5X1)",
    "originName":"1st Cache Milestone Coin and Tag Set",
    "updated":"2025-10-14 16:53:32",
    "owner":"CachingFoX",
    "publicCode":"TBAB0XK",
    "privateCode":"MSQ77C",
    "Unnamed: 9":"",
    "mainPicture":"milestone-1st-find.jpg",
    "note":"",
    "activateCode":"MILESTONE",
    "PIN":"",
    "tagsString":"Achievment",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/12474.gif",
    "name":"1000 Years Of Beer History In Prague - Meet & Greet Event Geocoin",
    "originName":"",
    "updated":"2025-10-15 08:11:50",
    "owner":"",
    "publicCode":"TBA8BX3",
    "privateCode":"CZZVWD",
    "Unnamed: 9":"",
    "mainPicture":"1000-years-of-beer-history-in-prague.jpg",
    "note":"Vorderseite: Mönch mit Bier vor einem Bierfass im Bierkeller. Schriftzug: 1000 Years of Beer History in Prague. Rückseite: Zwei Bierkrüge mit Schaum (farbig: gelb, weiß) stoßen an. Schriftzug: Meeting Geocaching Friends in Prague. Besonderheit: Aussparung als Flaschenöffner. Schr",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Prag, Tschechin, Bier",
    "collectionsString":"Essen und Trinken"
  },
  {
    "iconURL":"https:\/\/img.geocaching.com\/largeicon\/af8acdec-6606-4d71-997c-584ac12c041c.gif",
    "name":"The Globetrotter",
    "originName":"",
    "updated":"2025-10-14 16:08:30",
    "owner":"",
    "publicCode":"TBA8666",
    "privateCode":"GTTFWH",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/img.geocaching.com\/largeicon\/d03e7df3-c1b1-4b06-8054-2138f9dba931.gif",
    "name":"The Original Can of Beans",
    "originName":"",
    "updated":"2025-10-15 07:50:43",
    "owner":"",
    "publicCode":"TBA3BAJ",
    "privateCode":"OCVPW8",
    "Unnamed: 9":"",
    "mainPicture":"Can-of-Beans-AS-Side_600w_720x.jpg",
    "note":"Dose. Siehe auch OC48DE",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/img.geocaching.com\/largeicon\/d03e7df3-c1b1-4b06-8054-2138f9dba931.gif",
    "name":"The Original Can of Beans",
    "originName":"",
    "updated":"2025-10-15 07:50:44",
    "owner":"",
    "publicCode":"TBA3B1K",
    "privateCode":"OC48DE",
    "Unnamed: 9":"",
    "mainPicture":"Can-of-Beans-AS-Side_600w_720x.jpg",
    "note":"Decke der Dose. Siehe auch OC48DE",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/12220.gif",
    "name":"T-Rex 3d",
    "originName":"",
    "updated":"2025-10-13 14:45:02",
    "owner":"",
    "publicCode":"TBA21FV",
    "privateCode":"3DH6A8",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Dino",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/23.gif",
    "name":"Franconia Flag Micro",
    "originName":"",
    "updated":"2025-10-13 14:44:45",
    "owner":"",
    "publicCode":"TBA160G",
    "privateCode":"FXVEBN",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"FRANKEN",
    "PIN":"",
    "tagsString":"",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/10727.gif",
    "name":"EarthCache Fossil Tag",
    "originName":"",
    "updated":"2025-10-13 14:55:10",
    "owner":"",
    "publicCode":"TB9ZYPB",
    "privateCode":"EC16FP",
    "Unnamed: 9":"",
    "mainPicture":"fossil-tag-5_2.jpg",
    "note":"Zahn",
    "activateCode":"FOSSIL",
    "PIN":"",
    "tagsString":"",
    "collectionsString":"Earthcache"
  },
  {
    "iconURL":"https:\/\/img.geocaching.com\/largeicon\/fe7eadc7-1296-4623-8954-84827dfd8d9d.gif",
    "name":"Geoswag C&P Club March 2021 - Jurassic Geocoin",
    "originName":"",
    "updated":"2025-10-14 16:05:47",
    "owner":"",
    "publicCode":"TB9YGHZ",
    "privateCode":"GS9VE9",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Dino, Skelett, Fossil",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/3595.gif",
    "name":"Trekker the Hiking Boot Travel Tag",
    "originName":"",
    "updated":"2025-10-14 16:13:08",
    "owner":"",
    "publicCode":"TB9YEWD",
    "privateCode":"CBR00J",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Schuh, Stiefel, Wandern, Outdoor",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/9236.gif",
    "name":"EarthCache Tag",
    "originName":"",
    "updated":"2025-10-13 14:26:46",
    "owner":"",
    "publicCode":"TB9VBHQ",
    "privateCode":"ECTW47",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"EARTHCACHE",
    "PIN":"",
    "tagsString":"",
    "collectionsString":"Earthcache"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/23.gif",
    "name":"The Forces That Shape Our Earth Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:45:08",
    "owner":"",
    "publicCode":"TB9QBCP",
    "privateCode":"GS1WR4",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"Aufgeschnittene Erde mit verschiedenen Schichten, Ringe",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Element, Earth, Wind, Fire, Water",
    "collectionsString":"Earthcache"
  },
  {
    "iconURL":"https:\/\/img.geocaching.com\/largeicon\/e98c6619-16c8-448c-9784-be99902b6bd0.jpg",
    "name":"Spirit of Hawks",
    "originName":"",
    "updated":"2025-10-13 14:44:44",
    "owner":"",
    "publicCode":"TB9NZA3",
    "privateCode":"SHEMT2",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Vogel, Greifvogel",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/8414.gif",
    "name":"Travel Bug Origins Tag",
    "originName":"",
    "updated":"2025-10-13 14:44:46",
    "owner":"",
    "publicCode":"TB9NX3Q",
    "privateCode":"GSDCPT",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"ORIGINS",
    "PIN":"",
    "tagsString":"",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/23.gif",
    "name":"Cache Buddy Trekker",
    "originName":"Bavaria Flag Micro",
    "updated":"2025-10-13 14:45:18",
    "owner":"giacaches",
    "publicCode":"TB9NGA1",
    "privateCode":"GSGR96",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":"Nations and Regions"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/23.gif",
    "name":"Bavaria Flag Micro",
    "originName":"",
    "updated":"2025-10-13 14:45:17",
    "owner":"",
    "publicCode":"TB9NG8V",
    "privateCode":"GSHY5H",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":"Nations and Regions"
  },
  {
    "iconURL":"https:\/\/img.geocaching.com\/largeicon\/47d2fae4-8dc0-4c1d-a84a-07757efd26a1.gif",
    "name":"Pilsumer Leuchtturm Geocoin",
    "originName":"",
    "updated":"2025-10-14 16:13:07",
    "owner":"",
    "publicCode":"TB9H7KH",
    "privateCode":"TT1EEH",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"Leuchtturm",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Leuchtturm",
    "collectionsString":"Bauwerke"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/8326.gif",
    "name":"Die drei Fragezeichen Geocoin",
    "originName":"",
    "updated":"2025-10-15 08:33:52",
    "owner":"",
    "publicCode":"TB9GFQ5",
    "privateCode":"SBE33J",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"Kassette",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Staubfinger",
    "collectionsString":"Geocache"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/23.gif",
    "name":"Geoswag C&P Club August 2019 - Live in the Sunshine",
    "originName":"",
    "updated":"2025-10-15 07:57:45",
    "owner":"",
    "publicCode":"TB9EQFE",
    "privateCode":"GSMAV6",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"Vorderseite: Seestern als Relief in silber, im Hintergrund in antik bronze Seetiere, wie Muscheln, Schnecken. Schrifzug: Dring the Wild Air. Rückseite: Ammonit mit echten Sand, Seetiere im Relief Schriftzug: Live in the Sunshine. Swim in the Sea",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Ammonit, Fossil, Seestern, Meer, Tier, 2019",
    "collectionsString":"Geoswag Coin & Pin Club"
  },
  {
    "iconURL":"https:\/\/img.geocaching.com\/largeicon\/65bb67e3-ed62-4265-836b-95a02aa0c40b.gif",
    "name":"Dexters Buzzsaw Geocoin",
    "originName":"",
    "updated":"2025-10-15 08:30:58",
    "owner":"",
    "publicCode":"TB9DCT1",
    "privateCode":"PCTNY0",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"Kreissägenblatt. Mit Pin",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Staubfinger, Pin",
    "collectionsString":"Geocache"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/2518.gif",
    "name":"U.S. Flag Micro Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:45:20",
    "owner":"",
    "publicCode":"TB9CQ2J",
    "privateCode":"GS1DKC",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"USA",
    "collectionsString":"Nations and Regions"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/2294.gif",
    "name":"Virtual Ghost Micro Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:45:10",
    "owner":"",
    "publicCode":"TB9CQ18",
    "privateCode":"GSG8MA",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Icon",
    "collectionsString":"Geocache Types"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/11287.gif",
    "name":"Geocaching HQ Lackey 2019 Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:26:57",
    "owner":"",
    "publicCode":"TB9C823",
    "privateCode":"HQ3ANF",
    "Unnamed: 9":"",
    "mainPicture":"lackey-coin-2018.jpg",
    "note":"Lackeys Coin 2018. Ein Buch zum aufklappbar. Außenseite: Umgebung der Headquarters \/ Freemont, Gaswork Park, Troll Innenseite: Lackeys",
    "activateCode":"",
    "PIN":"",
    "tagsString":"2018",
    "collectionsString":"Headquarter"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/11287.gif",
    "name":"Geocaching HQ Lackey 2019 Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:27:02",
    "owner":"",
    "publicCode":"TB9C74M",
    "privateCode":"HQTVEW",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"Tag zu Lackey Coin 2018",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":"Headquarter"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/23.gif",
    "name":"National Topo Zion Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:26:48",
    "owner":"",
    "publicCode":"TB9ABE8",
    "privateCode":"GS3ZJW",
    "Unnamed: 9":"",
    "mainPicture":"National-Topo-Zion-Geocoin-Front_600w-1.jpg",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":"National Parks, USA"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/23.gif",
    "name":"National Topo Yellowstone Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:26:50",
    "owner":"",
    "publicCode":"TB9AB9D",
    "privateCode":"GS63G9",
    "Unnamed: 9":"",
    "mainPicture":"National-Topo-Yellowstone-Geocoin-Front_600w-2.jpg",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":"National Parks, USA"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/11105.gif",
    "name":"Mini Helmets",
    "originName":"",
    "updated":"2025-10-13 14:27:04",
    "owner":"",
    "publicCode":"TB99C1M",
    "privateCode":"GS6GBF",
    "Unnamed: 9":"",
    "mainPicture":"roman-imperial-helmet-3d-geocoin.jpg",
    "note":"Roman Imperial Helmet",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Römer, Gladiator",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/11105.gif",
    "name":"Mini Helmets",
    "originName":"",
    "updated":"2025-10-13 14:27:07",
    "owner":"",
    "publicCode":"TB99BRK",
    "privateCode":"GSXA8E",
    "Unnamed: 9":"",
    "mainPicture":"roman-centurion-helmet-3d-geocoin.jpg",
    "note":"Roman Centurion Helmet",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Römer, Gladiator",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/11105.gif",
    "name":"Mini Helmets",
    "originName":"",
    "updated":"2025-10-13 14:27:05",
    "owner":"",
    "publicCode":"TB99BMY",
    "privateCode":"GSN22E",
    "Unnamed: 9":"",
    "mainPicture":"roman-spiked-gladiator-helmet-3d-geocoin.jpg",
    "note":"Roman Skiped Gladiator Helmet",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Römer, Gladiator",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/11105.gif",
    "name":"Mini Helmets",
    "originName":"",
    "updated":"2025-10-13 14:27:06",
    "owner":"",
    "publicCode":"TB99B4R",
    "privateCode":"GSJ5R8",
    "Unnamed: 9":"",
    "mainPicture":"roman-battle-helmet-3d-geocoin.jpg",
    "note":"Roman Battle Helmet",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Römer, Gladiator",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/23.gif",
    "name":"National Topo Grand Canyon Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:26:53",
    "owner":"",
    "publicCode":"TB9989A",
    "privateCode":"GSK10H",
    "Unnamed: 9":"",
    "mainPicture":"National-Topo-Grand-Canyon-Geocoin-Front_600w-1.jpg",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":"National Parks, USA"
  },
  {
    "iconURL":"https:\/\/img.geocaching.com\/largeicon\/4d143b49-5121-40aa-95c0-a0c0ae90a8e5.gif",
    "name":"Zion Arrowhead Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:26:56",
    "owner":"",
    "publicCode":"TB997FV",
    "privateCode":"GSZTV9",
    "Unnamed: 9":"",
    "mainPicture":"Zion-Arrowhead-Geocoin-Antique-Bronze_600w.jpg",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Arrowhead",
    "collectionsString":"National Parks, USA"
  },
  {
    "iconURL":"https:\/\/img.geocaching.com\/largeicon\/c303e98a-f012-49bb-bb36-2d796a1f7563.gif",
    "name":"Grand Canyon Arrowhead Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:26:54",
    "owner":"",
    "publicCode":"TB9977Q",
    "privateCode":"GSQMNV",
    "Unnamed: 9":"",
    "mainPicture":"Grand-Canyon-Arrowhead-Geocoin-Antique-Bronze_600w.jpg",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Arrowhead",
    "collectionsString":"National Parks, USA"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/8002.gif",
    "name":"Geocaching HQ Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:26:59",
    "owner":"",
    "publicCode":"TB98V9C",
    "privateCode":"HQXHZZ",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Seattle,Riesenrad,Turm,Boot",
    "collectionsString":"Headquarter"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/23.gif",
    "name":"National Parks 100 Years Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:26:50",
    "owner":"",
    "publicCode":"TB98RX1",
    "privateCode":"GS9A9A",
    "Unnamed: 9":"",
    "mainPicture":"hat-national-parks-100-years-geocoin.jpg",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":"National Parks, USA"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/4218.gif",
    "name":"Waldkauz1977 &#9901; CachingFoX",
    "originName":"2 Hearts in Love Geocoin",
    "updated":"2025-10-15 08:28:14",
    "owner":"CachingFoX",
    "publicCode":"TB95NC2",
    "privateCode":"SBHZRR",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"Zwei Herzhälften als Anhänger. Verwendet für den TB Code im Ring",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":"Personal Item"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/4218.gif",
    "name":"CachingFoX &#9901; Waldkauz1977",
    "originName":"2 Hearts in Love Geocoin",
    "updated":"2025-10-15 08:28:15",
    "owner":"Waldkauz1977",
    "publicCode":"TB95N84",
    "privateCode":"SBFMB5",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"Zwei Herzhälften als Anhänger. Verwendet für den TB Code im Ring",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":"Personal Item"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/9097.gif",
    "name":"Beer Tag",
    "originName":"",
    "updated":"2025-10-14 16:13:11",
    "owner":"",
    "publicCode":"TB95G4E",
    "privateCode":"BT65CJ",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Bier",
    "collectionsString":"Essen und Trinken"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/3595.gif",
    "name":"Trekker the Hiking Boot Travel Tag",
    "originName":"",
    "updated":"2025-10-14 16:13:09",
    "owner":"",
    "publicCode":"TB94XGD",
    "privateCode":"CBTWBA",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Schuh, Stiefel, Wandern, Outdoor",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/8809.gif",
    "name":"Dexter Trinity Geocoin",
    "originName":"",
    "updated":"2025-10-15 08:33:51",
    "owner":"",
    "publicCode":"TB93JAV",
    "privateCode":"PCC3FX",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"Fleischer Messer",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Staubfinger",
    "collectionsString":"Geocache"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/10683.gif",
    "name":"Visit Geocaching HQ Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:44:59",
    "owner":"",
    "publicCode":"TB939KK",
    "privateCode":"HQE9NK",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"SEATTLE",
    "PIN":"",
    "tagsString":"",
    "collectionsString":"Headquarter"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/10727.gif",
    "name":"EarthCache Fossil Tag",
    "originName":"",
    "updated":"2025-10-13 14:26:43",
    "owner":"",
    "publicCode":"TB92R51",
    "privateCode":"ECC1A0",
    "Unnamed: 9":"",
    "mainPicture":"fossil-tag-3.jpg",
    "note":"Ammonit",
    "activateCode":"FOSSIL",
    "PIN":"",
    "tagsString":"",
    "collectionsString":"Earthcache"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/10727.gif",
    "name":"EarthCache Fossil Tag",
    "originName":"",
    "updated":"2025-10-13 14:26:44",
    "owner":"",
    "publicCode":"TB92QRW",
    "privateCode":"ECEA86",
    "Unnamed: 9":"",
    "mainPicture":"fossil-tag-1_1.jpg",
    "note":"Trilobiten",
    "activateCode":"FOSSIL",
    "PIN":"",
    "tagsString":"",
    "collectionsString":"Earthcache"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/10727.gif",
    "name":"EarthCache Fossil Tag",
    "originName":"",
    "updated":"2025-10-13 14:26:42",
    "owner":"",
    "publicCode":"TB92PXA",
    "privateCode":"EC16NP",
    "Unnamed: 9":"",
    "mainPicture":"fossil-tag-3.jpg",
    "note":"Fisch",
    "activateCode":"FOSSIL",
    "PIN":"",
    "tagsString":"",
    "collectionsString":"Earthcache"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/10727.gif",
    "name":"EarthCache Fossil Tag",
    "originName":"",
    "updated":"2025-10-13 14:26:45",
    "owner":"",
    "publicCode":"TB92PHN",
    "privateCode":"ECJQAX",
    "Unnamed: 9":"",
    "mainPicture":"fossil-tag-4_2.jpg",
    "note":"Foodprint",
    "activateCode":"FOSSIL",
    "PIN":"",
    "tagsString":"Dino",
    "collectionsString":"Earthcache"
  },
  {
    "iconURL":"https:\/\/img.geocaching.com\/largeicon\/d40d89f2-a35f-4ac6-ad7d-e86f4b40c8b5.gif",
    "name":"Yellowstone Arrowhead Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:26:49",
    "owner":"",
    "publicCode":"TB9250K",
    "privateCode":"GS5CG1",
    "Unnamed: 9":"",
    "mainPicture":"Yellowstone-Arrowhead-Geocoin-Antique-Bronze_600w.jpg",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Arrowhead",
    "collectionsString":"National Parks, USA"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/10682.gif",
    "name":"Bryan 2018 Founders Tag",
    "originName":"",
    "updated":"2025-10-13 14:26:52",
    "owner":"",
    "publicCode":"TB921FH",
    "privateCode":"GSCZ9C",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/8002.gif",
    "name":"Geocaching HQ Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:26:58",
    "owner":"",
    "publicCode":"TB8WR9Y",
    "privateCode":"HQ72ZP",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Seattle,Riesenrad,Turm,Boot",
    "collectionsString":"Headquarter"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/10126.gif",
    "name":"Ultimate Geocaching Trifecta Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:45:06",
    "owner":"",
    "publicCode":"TB8WNEZ",
    "privateCode":"TR98G6",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/9904.gif",
    "name":"Geocaching Trifecta Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:44:53",
    "owner":"",
    "publicCode":"TB8R8MA",
    "privateCode":"TRJ8KP",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"TRIFECTA",
    "PIN":"",
    "tagsString":"Mission 9, Original Stash, HQ",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/2316.gif",
    "name":"German Flag Micro Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:45:19",
    "owner":"",
    "publicCode":"TB8GGNQ",
    "privateCode":"GSRRXX",
    "Unnamed: 9":"",
    "mainPicture":"germany-micro-flag-geocoin.jpeg",
    "note":"Deutschland",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":"Nations and Regions"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/4283.gif",
    "name":"Travel Fish Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:45:16",
    "owner":"",
    "publicCode":"TB8AWQ5",
    "privateCode":"TFDQ0N",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Fisch, Skelett, Knochen",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/9339.gif",
    "name":"Roths 15 Year Anniversary Event Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:26:47",
    "owner":"",
    "publicCode":"TB87FK3",
    "privateCode":"EVRH3V",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/9244.gif",
    "name":"International EarthCache Day 2016 Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:45:07",
    "owner":"",
    "publicCode":"TB8632P",
    "privateCode":"ECP2E6",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Fossil, Dino, Skelett, Footprint",
    "collectionsString":"Earthcache, 2016"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/2380.gif",
    "name":"Letterbox Micro Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:45:09",
    "owner":"",
    "publicCode":"TB7RJYR",
    "privateCode":"GSGHB1",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Icon",
    "collectionsString":"Geocache Types"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/2815.gif",
    "name":"Webcam Micro Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:45:12",
    "owner":"",
    "publicCode":"TB7RJV8",
    "privateCode":"GSRNDG",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Icon",
    "collectionsString":"Geocache Types"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/23.gif",
    "name":"2016 Event Benchmark Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:26:51",
    "owner":"",
    "publicCode":"TB7PXPZ",
    "privateCode":"GSA92G",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"Benchmark Headquarter",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/2816.gif",
    "name":"Mystery Micro Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:45:11",
    "owner":"",
    "publicCode":"TB7PF7X",
    "privateCode":"GSJTM4",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Icon",
    "collectionsString":"Geocache Types"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/3247.gif",
    "name":"Locationless Micro Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:45:14",
    "owner":"",
    "publicCode":"TB7PF46",
    "privateCode":"GSQD5A",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Icon",
    "collectionsString":"Geocache Types"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/8411.gif",
    "name":"Dino Geocoin &#173; Velociraptor",
    "originName":"",
    "updated":"2025-10-14 16:22:59",
    "owner":"",
    "publicCode":"TB7MMR9",
    "privateCode":"DIC3T7",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Dino, Fossil, Skelett",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/8217.gif",
    "name":"Mega BigFoot Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:26:55",
    "owner":"",
    "publicCode":"TB7MF7H",
    "privateCode":"GSVGB7",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":"USA"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/2314.gif",
    "name":"Czech Republic Flag Micro Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:44:57",
    "owner":"",
    "publicCode":"TB7GZZN",
    "privateCode":"GSCYKH",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":"Nations and Regions"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/8189.gif",
    "name":"T5 Iceboots Geocoin",
    "originName":"",
    "updated":"2025-10-14 16:13:10",
    "owner":"",
    "publicCode":"TB7E2YG",
    "privateCode":"T5CK2H",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/3408.gif",
    "name":"Slovakia Flag Micro Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:44:56",
    "owner":"",
    "publicCode":"TB79ME0",
    "privateCode":"GSAP2Z",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":"Nations and Regions"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/3173.gif",
    "name":"Finnish Flag Micro Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:44:55",
    "owner":"",
    "publicCode":"TB79M6J",
    "privateCode":"GSQ11J",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":"Nations and Regions"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/2478.gif",
    "name":"France Flag Micro Geocoin",
    "originName":"",
    "updated":"2025-10-15 08:30:57",
    "owner":"",
    "publicCode":"TB79KVW",
    "privateCode":"GSPC25",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/4283.gif",
    "name":"Travel Fish Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:45:09",
    "owner":"",
    "publicCode":"TB73NPN",
    "privateCode":"TF0RTM",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Fisch, Skelett, Knochen",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/7286.gif",
    "name":"Caching Kitten Geocoin",
    "originName":"",
    "updated":"2025-10-16 21:16:59",
    "owner":"",
    "publicCode":"TB6NZA4",
    "privateCode":"CC3J2M",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"Katze sitzt auf einer Kiste",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Tier, Katze",
    "collectionsString":"Tiere"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/3099.gif",
    "name":"Traditional Micro",
    "originName":"",
    "updated":"2025-10-13 14:45:15",
    "owner":"",
    "publicCode":"TB6JWX1",
    "privateCode":"OC30FH",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Icon",
    "collectionsString":"Geocache Types"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/3166.gif",
    "name":"Swedish Flag Micro Geocoin",
    "originName":"",
    "updated":"2025-10-15 08:16:50",
    "owner":"",
    "publicCode":"TB6FPHE",
    "privateCode":"GSH86Z",
    "Unnamed: 9":"",
    "mainPicture":"swedish-micro-flag-geocoin_500.webp",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Flag, Sweden, Schweden",
    "collectionsString":"Nations and Regions"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/3995.gif",
    "name":"Walk for the Cure for Breast Cancer Geocoin",
    "originName":"",
    "updated":"2025-10-15 08:17:28",
    "owner":"",
    "publicCode":"TB6BDR5",
    "privateCode":"GS6N4A",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"Stilisiertes GPS Gerät in weiß auf rotem Untergrund",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/2488.gif",
    "name":"Lithuanian Flag Micro Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:44:58",
    "owner":"",
    "publicCode":"TB67JVQ",
    "privateCode":"GSVCQJ",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":"Nations and Regions"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/6300.gif",
    "name":"MegaBerlin 2013 Geocoin",
    "originName":"",
    "updated":"2025-10-14 16:05:41",
    "owner":"",
    "publicCode":"TB5WFQZ",
    "privateCode":"MBTPDQ",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"Mega Event Berlin \"Spuk unter dem Riesenrad\" GC44D2J",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Event, Mega, 2013",
    "collectionsString":"Events"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/5284.gif",
    "name":"Mammut Geocoin",
    "originName":"",
    "updated":"2025-10-14 16:05:46",
    "owner":"",
    "publicCode":"TB5CBV7",
    "privateCode":"MA7KJ7",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"Mammut Coin",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Skelett, Fossil, Mammut",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/4525.gif",
    "name":"Frängische Geocoin",
    "originName":"",
    "updated":"2025-10-14 16:05:42",
    "owner":"",
    "publicCode":"TB59DT3",
    "privateCode":"SBXKBG",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"Franken Coin Wein, Broodwärschd, Bier und Dubberdosen",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":"Nations and Regions"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/4707.gif",
    "name":"Dome Window Geocoin",
    "originName":"",
    "updated":"2025-10-16 21:16:06",
    "owner":"",
    "publicCode":"TB4MHFV",
    "privateCode":"ER3GRX",
    "Unnamed: 9":"Christina",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/2572.gif",
    "name":"GeoTriad Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:27:00",
    "owner":"",
    "publicCode":"TB4C1KA",
    "privateCode":"LSKT2D",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"GeoTriad - Successful Quest for the …",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Mission 9, Frosch, Signal, Original Stash, Baked Beans, APE, A.P.E.,Affe",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/3101.gif",
    "name":"Multi-Cache Micro",
    "originName":"",
    "updated":"2025-10-13 14:45:13",
    "owner":"",
    "publicCode":"TB3ZAKC",
    "privateCode":"OCC805",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Icon",
    "collectionsString":"Geocache Types"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/1325.gif",
    "name":"Waldkauz1977 Event Race Coin",
    "originName":"Geocacher&#39;s Day Geocoin",
    "updated":"2025-10-14 16:05:44",
    "owner":"Waldkauz1977",
    "publicCode":"TB3ATW5",
    "privateCode":"PCRHRP",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/1496.gif",
    "name":"Landsharkz Gecko Geocoin",
    "originName":"",
    "updated":"2025-10-16 21:17:27",
    "owner":"Waldkauz1977",
    "publicCode":"TB39ZV5",
    "privateCode":"LSTDT3",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/2570.gif",
    "name":"Mapamundi Geocoin (1st)",
    "originName":"Mapamundi Geocoin",
    "updated":"2025-10-14 16:05:48",
    "owner":"CachingFoX",
    "publicCode":"TB35YTB",
    "privateCode":"MM7DX2",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Kompassrose",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/21.gif",
    "name":"REMEMBER OPEL CORSA - ABWRACKPRÄMIE 2009 - DER ZWEITSCHLÜSSEL",
    "originName":"Travel Bug Dog Tag",
    "updated":"2025-10-14 16:13:06",
    "owner":"CachingFoX",
    "publicCode":"TB3395G",
    "privateCode":"63TTVD",
    "Unnamed: 9":"",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/2842.gif",
    "name":"GHOST TRAVELLER",
    "originName":"Geocaching Crystal Geocoin",
    "updated":"2025-10-16 21:15:23",
    "owner":"Waldkauz1977",
    "publicCode":"TB3058N",
    "privateCode":"NE0HNK",
    "Unnamed: 9":"Christina",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/1210.gif",
    "name":"Cheesocoin Geocoin",
    "originName":"",
    "updated":"2025-10-13 14:27:03",
    "owner":"",
    "publicCode":"TB22P9D",
    "privateCode":"ER9WPV",
    "Unnamed: 9":"Andreas",
    "mainPicture":"",
    "note":"cheescoin (se2) 2008, mit Löchern",
    "activateCode":"FROGLEY",
    "PIN":"",
    "tagsString":"",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/1538.gif",
    "name":"The Lord of the Caches - Earth Geocoin",
    "originName":"",
    "updated":"2025-10-16 21:13:18",
    "owner":"",
    "publicCode":"TB1Y84G",
    "privateCode":"LCY2JP",
    "Unnamed: 9":"Christina",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"",
    "collectionsString":""
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/4231.gif",
    "name":"CacheCat Geocoin",
    "originName":"",
    "updated":"2025-10-16 21:21:15",
    "owner":"",
    "publicCode":"TB5Q968",
    "privateCode":"PH4T3R",
    "Unnamed: 9":"Christina",
    "mainPicture":"",
    "note":"",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Katze",
    "collectionsString":"Tiere"
  },
  {
    "iconURL":"https:\/\/www.geocaching.com\/images\/WptTypes\/8258.gif",
    "name":"GeoCat Geocoin",
    "originName":"",
    "updated":"2025-10-16 21:39:54",
    "owner":"",
    "publicCode":"TB7H4RF",
    "privateCode":"GC3YBK",
    "Unnamed: 9":"Christina",
    "mainPicture":"",
    "note":"Tiger, Auflage 8\/50",
    "activateCode":"",
    "PIN":"",
    "tagsString":"Katze, Ring",
    "collectionsString":"Tiere"
  }
];
export { trackables };

